apiVersion: v1
kind: Service
metadata:
    name: "{{ default "meshery-practice-backend-a" .Values.backendA.name }}-service"
    labels:
        obj: service
        app: {{ default "meshery-practice-backend-a" .Values.backendA.labels.app }}
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
    selector:
        obj: pod
        app: {{ default "meshery-practice-backend-a" .Values.backendA.labels.app }}
    ports:
    - port: {{ default 5000 .Values.backendA.service.externalPort }}
      targetPort: {{ default 5000 .Values.backendA.service.internalPort | int }}
      protocol: "TCP"
    type: {{ default "ClusterIP" .Values.backendA.service.type }}