apiVersion: v1
kind: Service
metadata:
    name: "{{ default "meshery-practice-backendB" .Values.backendB.name }}-service"
    labels:
        obj: service
        app: {{ default "meshery-practice-backendB" .Values.backendB.labels.app }}
spec:
    selector:
        obj: pod
        app: {{ default "meshery-practice-backendB" .Values.backendB.labels.app }}
    ports:
    - port: {{ default 6000 .Values.backendB.service.externalPort }}
      targetPort: {{ default 6000 .Values.backendB.service.internalPort | int }}
      protocol: "TCP"
    type: {{ default "ClusterIP" .Values.backendB.service.type }}