apiVersion: v1
kind: ConfigMap
metadata:
    name: "{{ default "meshery-practice" .Values.configmap.name }}-configmap"
data:
    BACKEND_A: {{ default "http://backend-a.domain.com" .Values.configmap.BACKEND_A }}
    BACKEND_B: {{ default "http://backend-a.domain.com" .Values.configmap.BACKEND_B }}