apiVersion: app/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}-deployment"
  labels:
    obj: deployment
    app: {{ .Values.labels.app}}
spec:
  selector:
    matchLabels:
      app: {{ .Values.labels.app}}
  replicas: {{ default 1 .Values.replicas }}
  template:
    metadata:
      labels:
        obj: pod
        app: {{ .Values.labels.app }}
    spec:
      imagePullSecrets:
      - name: {{default "ghcr-secret" .Values.imagePullSecret}}
      containers:
      - name: "{{ .Values.name }}-container"
        image: "{{ .Values.image }}"
        imagePullPolicy: IfNotPresent
        env:
            {{- range .Values.configMapEnv }}
            - name: {{ .name }}
              valueFrom:
                configMapKeyRef:
                    name: {{ default "meshery-practice-configmap" .configMapName }}
                    key: {{ .value }}
            {{- end }}

            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
        livenessProbe:
          httpGet:
            path: {{ default "/" .Values.healthcheckPath}}
            port: {{ .Values.service.internalPort | int }}