apiVersion: v1
kind: Service
metadata:
    name: "{{ .Values.name }}-service"
    labels:
        obj: service
        app: {{ .Values.labels.app }}
spec:
    selector:
        obj: pod
        app: {{ .Values.labels.app }}
    ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort | int }}
      protocol: "TCP"
    type: {{ default "ClusterIP" .Values.service.type }}